[build-system]
requires =[
	"setuptools",
	"numpy"
]
build-backend ="setuptools.build_meta"

[project]
name ="DustyDisk"
dynamic =["version"]
dependencies=[
	"numpy",
	"matplotlib"
]

[tool.setuptools.dynamic]
version= {attr = "orbitize.__version__"}

[tool.setuptools.packages]

find ={}

